config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :articles
  resources :reservations
  resources :menu_parts
  match '/payments/:id',         to: 'payments#show', via: 'post'
  match '/hook',                 to: 'payments#hook', via: 'post' 
  resources :payments
  resources :menu_items
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match 'la-resto/',            to: 'la_resto#home', via: 'get' 
  match 'la-resto/about',       to: 'la_resto#about', via: 'get'
  match 'la-resto/menu',        to: 'la_resto#menu', via: 'get'
  match 'la-resto/reservation', to: 'la_resto#reservation', via: 'get'
  match 'la-resto/news',        to: 'la_resto#news', via: 'get'
  match 'la-resto/blog',        to: 'la_resto#blog', via: 'get'
  match 'la-resto/contacts',    to: 'la_resto#contacts', via: 'get'
  match 'signup',				to: 'users#new', via: 'get'
  match '/login', 				to: 'sessions#new', via: 'get'
  match '/logout',				to: 'sessions#destroy', via: 'delete' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/menu_part.rb
class MenuPart < ApplicationRecord
	has_many :menu_items
	has_attached_file :img, styles: { medium: "500x500>", thumb: "100x100>"}, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/	
end

app/controllers/menu_parts_controller.rb
class MenuPartsController < ApplicationController
  before_action :set_menu_part, only: [:show, :edit, :update, :destroy]

  # GET /menu_parts
  # GET /menu_parts.json
  def index
    @menu_parts = MenuPart.all
  end

  # GET /menu_parts/1
  # GET /menu_parts/1.json
  def show
  end

  # GET /menu_parts/new
  def new
    @menu_part = MenuPart.new
  end

  # GET /menu_parts/1/edit
  def edit
  end

  # POST /menu_parts
  # POST /menu_parts.json
  def create
    @menu_part = MenuPart.new(menu_part_params)

    respond_to do |format|
      if @menu_part.save
        format.html { redirect_to @menu_part, notice: 'Menu part was successfully created.' }
        format.json { render :show, status: :created, location: @menu_part }
      else
        format.html { render :new }
        format.json { render json: @menu_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_parts/1
  # PATCH/PUT /menu_parts/1.json
  def update
    respond_to do |format|
      if @menu_part.update(menu_part_params)
        format.html { redirect_to @menu_part, notice: 'Menu part was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu_part }
      else
        format.html { render :edit }
        format.json { render json: @menu_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_parts/1
  # DELETE /menu_parts/1.json
  def destroy
    @menu_part.destroy
    respond_to do |format|
      format.html { redirect_to menu_parts_url, notice: 'Menu part was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show_image
    @menu_part = MenuPart.find(params[:id])
    send_data @menu_part.img, type: 'image/jpeg', disposition: 'attachment'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu_part
      @menu_part = MenuPart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_part_params
      params.require(:menu_part).permit(:name, :img)
    end
end

app/helpers/menu_parts_helper.rb
module MenuPartsHelper
end

app/views/menu_parts/_form.html.erb
<%= form_for(menu_part) do |f| %>
  <% if menu_part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu_part.errors.count, "error") %> prohibited this menu_part from being saved:</h2>

      <ul>
      <% menu_part.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="field form-group file-field form-control">
    <div class="file-field__select">Выбрать файл</div>
    <div class="file-field__file-name">Файл не выбран</div>
    <%= f.file_field :img, class: "file-field__input" %>
  </div>

  <div class="actions form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/menu_parts/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-4">
			<h1>Editing Menu Part</h1>

			<%= render 'form', menu_part: @menu_part %>

			<%= link_to 'Show', @menu_part %> |
			<%= link_to 'Back', menu_parts_path %>
		</div>
	</div>	
</div>

app/views/menu_parts/index.html.erb
<div class="container">
  <div class="row">
    <h1>Menu Parts</h1>

    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Image</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @menu_parts.each do |menu_part| %>
          <tr>
            <td><%= menu_part.name %></td>
            <td><%= image_tag menu_part.img.url(:thumb) %></td>
            <td><%= link_to 'Show', menu_part %></td>
            <td><%= link_to 'Edit', edit_menu_part_path(menu_part) %></td>
            <td><%= link_to 'Destroy', menu_part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Menu Part', new_menu_part_path %>
    
  </div>
</div>

app/views/menu_parts/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-4">
			<h1>New Menu Part</h1>

			<%= render 'form', menu_part: @menu_part %>

			<%= link_to 'Back', menu_parts_path %>
		</div>
	</div>
</div>

app/views/menu_parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @menu_part.name %>
  <%= image_tag @menu_part.img.url(:medium) %>
</p>

<%= link_to 'Edit', edit_menu_part_path(@menu_part) %> |
<%= link_to 'Back', menu_parts_path %>