config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :articles
  resources :reservations
  resources :menu_parts
  match '/payments/:id',         to: 'payments#show', via: 'post'
  match '/hook',                 to: 'payments#hook', via: 'post' 
  resources :payments
  resources :menu_items
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match 'la-resto/',            to: 'la_resto#home', via: 'get' 
  match 'la-resto/about',       to: 'la_resto#about', via: 'get'
  match 'la-resto/menu',        to: 'la_resto#menu', via: 'get'
  match 'la-resto/reservation', to: 'la_resto#reservation', via: 'get'
  match 'la-resto/news',        to: 'la_resto#news', via: 'get'
  match 'la-resto/blog',        to: 'la_resto#blog', via: 'get'
  match 'la-resto/contacts',    to: 'la_resto#contacts', via: 'get'
  match 'signup',				to: 'users#new', via: 'get'
  match '/login', 				to: 'sessions#new', via: 'get'
  match '/logout',				to: 'sessions#destroy', via: 'delete' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/payment.rb
class Payment < ApplicationRecord
	belongs_to :user
	has_many :menu_items

	serialize :notification_params, Hash
	def paypal_url(return_url)
		values = {
			cmd: '_xclick',
			charset: 'utf-8',
			business: 'ghostlinee-facilitator@gmail.com',
			return: "#{Rails.application.secrets.app_host}#{return_url}",
			invoice: id,
			item_number: 2,
			item_name: 'name',
			currency_code: 'RUB', 
			amount: 100,
			notify_url: "#{Rails.application.secrets.app_host}/hook"
		}
		"#{Rails.application.secrets.paypal_host}/cgi-bin/websrc?#{values.to_query}"
	end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]
  protect_from_forgery except: [:hook]
  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end
  
  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)
    @payment.user = User.find(1)
    respond_to do |format|
      if @payment.save
        
        format.html { redirect_to @payment.paypal_url(payment_path(@payment)), notice: 'Payment was successfully created.' }
        #format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def hook
    params.permit!
    status = params[:payment_status]
    if status == "Completed"
      @payment = Payment.find params[:invoice]
      @payment.update_attributes(notification_params: params.to_h, status: status, 
                                  transaction_id: params[:txn_id], 
                                  purchased_at: Time.now)
    end
    render nothing: true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.fetch(:payment, {})
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper

	
end

app/views/payments/_form.html.erb
<%= form_for(payment) do |f| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>