config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :articles
  resources :reservations
  resources :menu_parts
  match '/payments/:id',         to: 'payments#show', via: 'post'
  match '/hook',                 to: 'payments#hook', via: 'post' 
  resources :payments
  resources :menu_items
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match 'la-resto/',            to: 'la_resto#home', via: 'get' 
  match 'la-resto/about',       to: 'la_resto#about', via: 'get'
  match 'la-resto/menu',        to: 'la_resto#menu', via: 'get'
  match 'la-resto/reservation', to: 'la_resto#reservation', via: 'get'
  match 'la-resto/news',        to: 'la_resto#news', via: 'get'
  match 'la-resto/blog',        to: 'la_resto#blog', via: 'get'
  match 'la-resto/contacts',    to: 'la_resto#contacts', via: 'get'
  match 'signup',				to: 'users#new', via: 'get'
  match '/login', 				to: 'sessions#new', via: 'get'
  match '/logout',				to: 'sessions#destroy', via: 'delete' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_attached_file :img, styles: { medium: "500x500>", thumb: "100x100>"}, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
	has_one :payment
	belongs_to :menu_part
	has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>"}, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/	
	validates :name, presence: true, length: { maximum: 50 }
	validates :cost, presence: true, numericality: { greater_than: 0 }
end

app/models/menu_part.rb
class MenuPart < ApplicationRecord
	has_many :menu_items
	has_attached_file :img, styles: { medium: "500x500>", thumb: "100x100>"}, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/	
end

app/models/payment.rb
class Payment < ApplicationRecord
	belongs_to :user
	has_many :menu_items

	serialize :notification_params, Hash
	def paypal_url(return_url)
		values = {
			cmd: '_xclick',
			charset: 'utf-8',
			business: 'ghostlinee-facilitator@gmail.com',
			return: "#{Rails.application.secrets.app_host}#{return_url}",
			invoice: id,
			item_number: 2,
			item_name: 'name',
			currency_code: 'RUB', 
			amount: 100,
			notify_url: "#{Rails.application.secrets.app_host}/hook"
		}
		"#{Rails.application.secrets.paypal_host}/cgi-bin/websrc?#{values.to_query}"
	end
end

app/models/post.rb
class Post < ApplicationRecord
	has_attached_file :img, styles: { medium: "500x500>", thumb: "100x100>"}, default_url: "/images/:style/missing.png"
end

app/models/reservation.rb
class Reservation < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	before_save {self.email = email.downcase }
	before_create :create_remember_token
	validates :name, presence: true, length: { maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true , format: { with: VALID_EMAIL_REGEX},
		uniqueness: {case_sensitive: false}
	validates :password, length: { minimum: 6}
	has_secure_password
	has_many :payments

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :short_descrition, :descriotion)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
 

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/la_resto_helper.rb
module LaRestoHelper
	
	def separator_block(size = 12, modificator = false)
		cl = "separator col-sm-#{size} "
		cl += "separator_inverse" if modificator == true
		separator = content_tag(:div, "" , class: cl )
		content_tag(:div, 
			content_tag(:div, separator , class: 'row'), class: 'container-fluid') 
	end

end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/menu_parts_helper.rb
module MenuPartsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper

	
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def logout
		current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
		cookies.delete(:remember_token)
		self.current_user = nil
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="row">
	<footer>
		<div class="container-fluid">
			<div class="row">
				<div class="widgets">
					<%= link_to "" do %>
						<i class="fa fa-facebook fa-lg" aria-hidden="true"></i>	
					<% end %>
					<%= link_to "" do %>
						<i class="fa fa-google-plus fa-lg" aria-hidden="true"></i>
					<%end%>
					<%= link_to "" do %>
						<i class="fa fa-twitter fa-lg" aria-hidden="true"></i>
					<%end%>
					<%= link_to "" do %>
						<i class="fa fa-linkedin fa-lg" aria-hidden="true"></i>
					<%end%>
					
				</div>
			</div>
		</div>
		<div class="container-fluid">
			<div class="row">
				All Rights Reserved ©  La Resto 2016  |  Privacy Policy
			</div>
		</div>
	</footer>
</div>

app/views/layouts/_header.html.erb
<% if !header_root.empty? %>
<header class="container-fluid navbar-fixed-top header">
	<div class="row">
		<div class="col-sm-12">
<% else %>
<header class="container-fluid navbar-fixed-top header header_general">
	<div class="row">
		<div class="col-sm-3 header__logo-small">
			<div class="row">
			<%= link_to(la_resto_path) do %>
				<div class="col-sm-4">
				<%= image_tag("logo-small.png") %>
				</div>
				<div class="col-sm-8 header__logo-text">
					<div class="row">
						LA RESTO
					</div>
					<div class="row header__text-undertitle">
						LIKE NO PLACE
					</div>
					
				</div>
			</div>
			<% end %>
		</div>
		<div class="col-sm-9">
<% end %>
			<ul class="nav navbar-nav header__menu">
				<li><%= link_to "ABOUT", la_resto_about_path %></li>
				<li><%= link_to "MENU", la_resto_menu_path %></li>
				<li><%= link_to "RESERVATION", la_resto_reservation_path %></li>
				<li><%= link_to "NEWS", la_resto_news_path %></li>
				<li><%= link_to "BLOG", la_resto_blog_path %></li>
				<li><%= link_to "CONTACTS", la_resto_contacts_path %></li>
				<% if signed_in? %>
					<li><%= link_to "LOGOUT", logout_path, method: "delete" %></li>
				<% else %>
					<li><%= link_to "SIGN UP", signup_path %></li>
					<li><%= link_to "LOGIN", login_path %></li>
				<% end %>
			</ul>
		</div>
	</div>	
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp | <%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   
  </head>
  <body>
  	<%= render 'layouts/header', header_root: yield(:header_root) %>
  	<%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@user.errors.count, "error") %>.
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li>* <%= msg %> </li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_under_construction.html.erb
<div class="container-fluid">
	<div class="row under-construction">
		<div class="col-sm-offset-3 col-sm-6">
			<div class="under-construction__title">
				Page Under Construction
			</div>
		</div>
	</div>
</div>